import END_POINTS from './endpoint';
import {
  SUBJECT_EMAIL_SIGNUP,
  TEMPLATE_EMAIL_SIGNUP,
  TEMPLATE_EMAIL_RESET_PASS,
  SUBJECT_EMAIL_RESET_PASS,
} from './email';

enum EGender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

enum ERole {
  ADMIN = 'ADMIN',
  USER = 'USER',
  MODERATOR = 'MODERATOR',
}

const EXPIRE_TOKEN = {
  ACCESS_TOKEN: '8h',
  REFRESH_TOKEN: '7day',
  RESET_PASS_TOKEN: '2m',
  NUMBER_ACCESS_TOKEN: 8 * 60 * 60 * 1000,
  NUMBER_REFRESH_TOKEN: 7 * 24 * 60 * 60 * 1000,
  NUMBER_RESET_PASS_TOKEN: 2 * 60 * 1000,
};

const CONSTANTS = {
  EGender,
  ERole,
  END_POINTS,
  SUBJECT_EMAIL_SIGNUP,
  TEMPLATE_EMAIL_SIGNUP,
  EXPIRE_TOKEN,
  SUBJECT_EMAIL_RESET_PASS,
  TEMPLATE_EMAIL_RESET_PASS,
};

export default CONSTANTS;
